language: csharp
solution: NameSorter.sln
install:
  - nuget restore NameSorter.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release NameSorter.sln
  - .NameSorter/NameSorterTest/bin/Debug/netcoreapp3.1/NameSorterTest.dll
